"""add location constraint and records default

Revision ID: 3dde20f33bee
Revises: a014aa729b72
Create Date: 2026-08-23 21:16:47.910932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dde20f33bee'
down_revision: Union[str, Sequence[str], None] = 'a014aa729b72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'locations', ['city', 'country_code', 'latitude', 'longitude'])
    op.alter_column(
        'pipeline_runs',
        'records_processed',
        existing_type=sa.Integer(),
        server_default=sa.text('0'),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'pipeline_runs',
        'records_processed',
        existing_type=sa.Integer(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_constraint(None, 'locations', type_='unique')
    # ### end Alembic commands ###