"""create initial database tables

Revision ID: a014aa729b72
Revises: 
Create Date: 2026-08-23 16:00:22.955097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a014aa729b72'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table('locations',
  sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
  sa.Column('city', sa.String(), nullable=False),
  sa.Column('country_code', sa.String(length=2), nullable=False),
  sa.Column('state', sa.String(), nullable=True),
  sa.Column('latitude', sa.Float(), nullable=False),
  sa.Column('longitude', sa.Float(), nullable=False),
  sa.CheckConstraint('latitude >= -90 AND latitude <= 90'),
  sa.CheckConstraint('length(country_code) = 2'),
  sa.CheckConstraint('longitude >= -180 AND longitude <= 180'),
  sa.PrimaryKeyConstraint('id')
  )
  op.create_table('pipeline_runs',
  sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
  sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
  sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
  sa.Column('status', sa.String(), nullable=False),
  sa.Column('records_processed', sa.Integer(), nullable=False),
  sa.Column('error_message', sa.String(), nullable=True),
  sa.CheckConstraint("status IN ('running', 'success', 'failed')"),
  sa.CheckConstraint('records_processed >= 0'),
  sa.PrimaryKeyConstraint('id')
  )
  op.create_table('air_quality_records',
  sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
  sa.Column('location_id', sa.BigInteger(), nullable=False),
  sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
  sa.Column('aqi', sa.SmallInteger(), nullable=False),
  sa.Column('pm2_5', sa.Float(), nullable=True),
  sa.Column('pm10', sa.Float(), nullable=True),
  sa.Column('no2', sa.Float(), nullable=True),
  sa.Column('o3', sa.Float(), nullable=True),
  sa.CheckConstraint('aqi >= 1 AND aqi <= 5'),
  sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
  sa.PrimaryKeyConstraint('id'),
  sa.UniqueConstraint('location_id', 'observed_at')
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table('air_quality_records')
  op.drop_table('pipeline_runs')
  op.drop_table('locations')
  # ### end Alembic commands ###